flask:
    host: 0.0.0.0
    debug: True

client:
    host: 0.0.0.0
    port: 1337

errors:
   default: 'We''re sorry but something seems to have gone wrong at our end. Try again later.'
   ActionError: 'Failed to run action. Reply with ''help'' for a list of available actions.'
   InvalidActionError: 'Invalid action. Reply with ''help'' for a list of available actions.'
